[project]
name = "tea-backend"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "pymysql",
    "pydantic",
    "python-jose[cryptography]",
    "passlib[bcrypt]",
    "bcrypt==3.2.2",
    "python-multipart",
    "python-dotenv",
    "email-validator",
    "gunicorn",
    "phonepe_sdk",
    "setuptools",
    "jinja2>=3.1.6",
    "cloudinary",
]

[[tool.uv.index]]
name = "phonepe"
url = "https://phonepe.mycloudrepo.io/public/repositories/phonepe-pg-sdk-python"
explicit = true

[tool.uv.sources]
phonepe-sdk = { index = "phonepe" }
